housing <- read.csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv")
head(housing)
View(housing)
library(GGally)
ggpairs(housing)
head(housing)
m<-lm(crim~zn+indus+nox+rm+age+dis+rad+tax+ptratio+b+lstat+medv,data = housing)
library(performance)
check_model(m)
library(DAAG)
vif(m)
m1<-lm(crim~zn+indus+nox+rm+age+dis+rad+ptratio+b+lstat+medv,data = housing)
vif(m1)
library(olsrr)
m2<-ols_step_best_subset(m1)
m2

m3<-lm(log(crim)~sqrt(zn)+nox+dis+rad+log(ptratio)+b+lstat+medv,data = housing)
m4<-lm(log(crim)~zn+indus+nox+dis+rad+ptratio+b+lstat+medv,data = housing )
summary(m3)
plot(m4,5)
library(car)
ncvTest(m4)
