housing <- read.csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv")
head(housing)
View(housing)
library(GGally)
ggpairs(housing)
model_F<-lm(rm~., data=housing)
summary(model_F)
# db<-housing[housing,-chas]

md<-lm(crim~rm+zn+indus+nox+age +dis+rad+ ptratio+b+lstat+medv,data = housing )
summary(md)
library(DAAG)
vif(md)
library(olsrr)
m1<-ols_step_best_subset(md)
m1
library(performance)
m_aic<-lm(log(crim)~sqrt(zn)+nox+dis+rad+sqrt(ptratio)+b+lstat+medv,data=housing)
summary(m_aic)
plot(m_aic,1)
pdf("_check_model 2.pdf", width = 10, height = 8)
check_model(m_aic)
plot(m_aic,1)
plot(m_aic,2)
plot(m_aic,3)
plot(m_aic,4)
plot(m_aic,5)
dev.off()



m_ajr2<-lm(log(crim)~sqrt(zn)+indus+nox+dis+rad+log(ptratio)+b+lstat+medv,data=housing)
summary(m_ajr2)
library(car)
ncvTest(m_ajr2)
summary(m_ajr2)
plot(m_ajr2,1)
# library(performance)
check_model(m_ajr2)
png("m_ajr2",width = 1200,height=1600)
check_model(m_ajr2)
dev.off()
pdf("_check_model.pdf", width = 10, height = 8)
check_model(m_ajr2)
plot(m_ajr2,1)
plot(m_ajr2,2)
plot(m_ajr2,3)
plot(m_ajr2,4)
plot(m_ajr2,5)
dev.off()


